export const PROFILE = ['profile']
export const UPDATE_PROFILE = ['update_profile']
export const USER_LIST = ['user.list']
export const USER_ADD = ['user.store']
export const USER_DELETE = ['user.delete']
export const USER_DELETE_MULTI = ['user.force_delete_multi']
export const USER_RESTORE = ['user.restore', 'user.restore_multi']
export const USER_UPDATE = ['user.show', 'user.update']
export const USER_IMPORT = []

export const EVENT_LIST = ['event.getType', 'event.list']
export const EVENT_ADD = ['event.getType', 'event.store']
export const EVENT_DELETE = ['event.delete']
export const EVENT_UPDATE = ['event.edit', 'event.update']

export const ROLE_LIST = ['role.list']
export const ROLE_ADD = ['role.create']
export const ROLE_DELETE = ['role.delete']
export const ROLE_UPDATE = ['role.detail', 'role.update']

export const TEAM_LIST = ['team.list']
export const TEAM_ADD = ['team.create', 'team.getAllMainTeam']
export const TEAM_UPDATE = ['team.update', 'team.getDetail']
export const TEAM_DELETE = ['team.delete']
export const TEAM_ADD_MEMBER = ['team.addMember']
export const TEAM_DELETE_MEMBER = ['team.removeMember']
export const TEAM_LIST_SUB = ['team.getAllListSub']
export const TEAM_LIST_MEMBER = ['team.listSub', 'team.getListUser']

export const ATTENDANCE_LIST = ['attendance.list']
export const ATTENDANCE_ADD = ['attendance.store']
export const ATTENDANCE_DELETE = ['attendance.delete']
export const ATTENDANCE_UPDATE = ['attendance.update', 'attendance.show']
export const ATTENDANCE_REVIEW = ['attendance.accept', 'attendance.reject']
export const ATTENDANCE_EXPORT = ['attendance.export']
export const ATTENDANCE_IMPORT = [
  'attendance.importAttendance',
  'attendance.exportTemplate',
]
export const ATTENDANCE_EXPORT_TEMPLATE = ['attendance.exportTemplate']
