export const PROFILE = ['profile']
export const UPDATE_PROFILE = ['update_profile']
export const USER_LIST = ['user.list']
export const USER_LIST_DELETED = ['user.list_deleted']
export const USER_ADD = ['user.store']
export const USER_DELETE = ['user.delete']
export const USER_FORCE_DELETE = ['user.force_delete']
// export const USER_DELETE_MULTI = ['user.force_delete_multi']
export const USER_RESTORE = ['user.restore']
export const USER_UPDATE = ['user.update']
export const USER_IMPORT = ['user.import_user']
export const USER_IMPORT_VIEW = ['user.import_user']

export const EVENT_LIST = ['event.list']
export const EVENT_ADD = ['event.store']
export const EVENT_DELETE = ['event.delete']
export const EVENT_UPDATE = ['event.update']

export const ROLE_LIST = ['role.list']
export const ROLE_ADD = ['role.create']
export const ROLE_DELETE = ['role.delete']
export const ROLE_UPDATE = ['role.update']

export const TEAM_LIST = ['team.list']
export const TEAM_ADD = ['team.create']
export const TEAM_UPDATE = ['team.update']
export const TEAM_DELETE = ['team.delete']
export const TEAM_ADD_MEMBER = ['team.addMember']
export const TEAM_DELETE_MEMBER = ['team.removeMember']
export const TEAM_LIST_SUB = ['team.getAllListSub']
export const TEAM_LIST_MEMBER = ['team.getListUser']

export const ATTENDANCE_LIST = ['attendance.list']
export const ATTENDANCE_ADD = ['attendance.store']
export const ATTENDANCE_DELETE = ['attendance.delete']
export const ATTENDANCE_UPDATE = ['attendance.update']
export const ATTENDANCE_REVIEW = ['attendance.accept', 'attendance.reject']
export const ATTENDANCE_EXPORT = ['attendance.export']
export const ATTENDANCE_IMPORT = [
  'attendance.import',
  'attendance.exportTemplate',
]
export const ATTENDANCE_EXPORT_VIEW = ['attendance.importedList']
